/* wickra-exchange C ABI — generated by cbindgen. Do not edit by hand. */

#ifndef WICKRA_EXCHANGE_H
#define WICKRA_EXCHANGE_H

#pragma once

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Success.
 */
#define WICKRA_OK 0

/**
 * A required pointer argument was null.
 */
#define WICKRA_ERR_NULL -1

/**
 * An argument was invalid (bad market string, non-finite number, bad UTF-8).
 */
#define WICKRA_ERR_INVALID_ARG -2

/**
 * The operation is not supported on this backend (e.g. `set_price` off paper).
 */
#define WICKRA_ERR_UNSUPPORTED -3

/**
 * The account had insufficient balance for the request.
 */
#define WICKRA_ERR_INSUFFICIENT_BALANCE -4

/**
 * The referenced order or entity was not found.
 */
#define WICKRA_ERR_NOT_FOUND -5

/**
 * The order was rejected by the venue / simulator.
 */
#define WICKRA_ERR_REJECTED -6

/**
 * Any other error reported by the exchange layer.
 */
#define WICKRA_ERR_OTHER -7

/**
 * Order side: buy.
 */
#define WICKRA_SIDE_BUY 0

/**
 * Order side: sell.
 */
#define WICKRA_SIDE_SELL 1

/**
 * Order status codes (mirror `OrderStatus`).
 */
#define WICKRA_STATUS_NEW 0

#define WICKRA_STATUS_PARTIALLY_FILLED 1

#define WICKRA_STATUS_FILLED 2

#define WICKRA_STATUS_CANCELED 3

#define WICKRA_STATUS_REJECTED 4

#define WICKRA_STATUS_EXPIRED 5

/**
 * Stream event kinds.
 */
#define WICKRA_EVENT_TRADE 0

#define WICKRA_EVENT_TICKER 1

#define WICKRA_EVENT_ORDER_UPDATE 2

#define WICKRA_EVENT_BALANCE_UPDATE 3

#define WICKRA_EVENT_SUBSCRIBED 4

#define WICKRA_EVENT_OTHER 5

/**
 * Fixed capacity (including the NUL terminator) of the C-string fields in the
 * `#[repr(C)]` result structs.
 */
#define WICKRA_STR_CAP 64

/**
 * An opaque exchange handle. Construct with `wickra_paper_new` /
 * `wickra_replay_new` / `wickra_connect`; release with `wickra_exchange_free`.
 */
typedef struct WickraExchange WickraExchange;

/**
 * An order as reported by the exchange (C-ABI mirror of `Order`).
 */
typedef struct {
    /**
     * Venue order id, NUL-terminated (truncated to `WICKRA_STR_CAP - 1` bytes).
     */
    char id[WICKRA_STR_CAP];
    /**
     * `WICKRA_SIDE_*`.
     */
    int32_t side;
    /**
     * `WICKRA_STATUS_*`.
     */
    int32_t status;
    /**
     * Total ordered quantity.
     */
    double quantity;
    /**
     * Quantity filled so far.
     */
    double filled_quantity;
    /**
     * Limit price, or `NaN` if none.
     */
    double price;
    /**
     * Average fill price, or `NaN` if none.
     */
    double average_price;
} WickraOrder;

/**
 * A single stream event (C-ABI projection of `Event`).
 */
typedef struct {
    /**
     * `WICKRA_EVENT_*`.
     */
    int32_t kind;
    /**
     * Market symbol for trade/ticker events, NUL-terminated (empty otherwise).
     */
    char symbol[WICKRA_STR_CAP];
    /**
     * Price for trade/ticker events (`NaN` otherwise).
     */
    double price;
    /**
     * Quantity for trade events (`NaN` otherwise).
     */
    double quantity;
    /**
     * `WICKRA_SIDE_*` for trade events (`-1` otherwise).
     */
    int32_t side;
    /**
     * The order for `order_update` events.
     */
    WickraOrder order;
} WickraEvent;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * The library version as a static NUL-terminated string.
 */
const char *wickra_version(void);

/**
 * Construct an offline paper account seeded from parallel `assets`/`amounts`
 * arrays (length `n_balances`). Returns null on invalid arguments.
 *
 * # Safety
 * The array pointers must be valid for `n_balances` elements (or null when it
 * is zero).
 */
WickraExchange *wickra_paper_new(const char *const *assets,
                                 const double *amounts,
                                 uintptr_t n_balances,
                                 double maker_bps,
                                 double taker_bps,
                                 double slippage_bps);

/**
 * Construct a replay account driven by a `tape` of `n_tape` trade prices for
 * `market`, filling a paper book seeded from `assets`/`amounts`. Returns null on
 * invalid arguments.
 *
 * # Safety
 * `market` must be a valid C string; the array pointers must be valid for their
 * stated lengths (or null when zero).
 */
WickraExchange *wickra_replay_new(const char *market,
                                  const double *tape,
                                  uintptr_t n_tape,
                                  const char *const *assets,
                                  const double *amounts,
                                  uintptr_t n_balances,
                                  double maker_bps,
                                  double taker_bps,
                                  double slippage_bps);

/**
 * Connect a live client for `name`, authenticated with the given credentials
 * (`passphrase`/`private_key` may be null). Returns null on failure.
 *
 * # Safety
 * The non-null string arguments must be valid C strings.
 */
WickraExchange *wickra_connect(const char *name,
                               const char *api_key,
                               const char *api_secret,
                               const char *passphrase,
                               const char *private_key,
                               bool testnet);

/**
 * Release an exchange handle. Safe to call with null.
 *
 * # Safety
 * `handle` must be null or a pointer returned by a `wickra_*_new` / `wickra_connect`
 * constructor, freed exactly once.
 */
void wickra_exchange_free(WickraExchange *handle);

/**
 * Write the venue name into `out` (capacity `cap`, always NUL-terminated).
 *
 * # Safety
 * `handle` must be valid; `out` must be writable for `cap` bytes.
 */
int32_t wickra_exchange_name(const WickraExchange *handle, char *out, uintptr_t cap);

/**
 * Set the mark price a paper account fills against (paper backend only).
 *
 * # Safety
 * `handle` must be valid; `market` must be a valid C string.
 */
int32_t wickra_exchange_set_price(WickraExchange *handle, const char *market, double price);

/**
 * Place a market order (`side` is `WICKRA_SIDE_*`); writes the resulting order
 * into `out`.
 *
 * # Safety
 * `handle` and `out` must be valid; `market` must be a valid C string.
 */
int32_t wickra_exchange_place_market(WickraExchange *handle,
                                     const char *market,
                                     int32_t side,
                                     double quantity,
                                     WickraOrder *out);

/**
 * Place a limit order (`side` is `WICKRA_SIDE_*`) at `price`; writes the
 * resulting order into `out`.
 *
 * # Safety
 * `handle` and `out` must be valid; `market` must be a valid C string.
 */
int32_t wickra_exchange_place_limit(WickraExchange *handle,
                                    const char *market,
                                    int32_t side,
                                    double quantity,
                                    double price,
                                    WickraOrder *out);

/**
 * Cancel an open order by venue id.
 *
 * # Safety
 * `handle` must be valid; `market` and `order_id` must be valid C strings.
 */
int32_t wickra_exchange_cancel(WickraExchange *handle, const char *market, const char *order_id);

/**
 * Write the free balance of `asset` into `*out_free`.
 *
 * # Safety
 * `handle` and `out_free` must be valid; `asset` must be a valid C string.
 */
int32_t wickra_exchange_balance(WickraExchange *handle, const char *asset, double *out_free);

/**
 * Drain buffered events into `out` (capacity `cap`). Returns the number written
 * (`>= 0`) or a negative error code.
 *
 * # Safety
 * `handle` must be valid; `out` must be writable for `cap` elements.
 */
int32_t wickra_exchange_poll(WickraExchange *handle, WickraEvent *out, uintptr_t cap);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* WICKRA_EXCHANGE_H */
