/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * A live advanced-orders client: amend, batch place/cancel and OCO. Available
 * on the eight trading venues (native where supported, else a thrown error).
 */
export declare class AdvancedOrders {
  /**
   * Connect an advanced-orders client for `name`. `futures` selects the
   * USDⓈ-M futures market. Throws for a venue without an advanced-order surface.
   */
  static connect(name: string, credentials: Credentials, testnet?: boolean | undefined | null, futures?: boolean | undefined | null): AdvancedOrders
  /**
   * Amend a resting order's price and/or quantity in place; `null`/`undefined`
   * leaves that field unchanged. Returns the refreshed order.
   */
  amendOrder(market: string, orderId: string, newPrice?: number | undefined | null, newQuantity?: number | undefined | null): OrderInfo
  /** Cancel several orders on `market` in one request. */
  cancelBatch(market: string, orderIds: Array<string>): void
  /**
   * Place a one-cancels-other bracket (take-profit `price` + `stopPrice`
   * trigger, optional `stopLimitPrice`); returns the resulting order legs.
   */
  placeOco(market: string, side: string, quantity: number, price: number, stopPrice: number, stopLimitPrice?: number | undefined | null): Array<OrderInfo>
  /**
   * Place several orders in one request. Takes an array of `OrderRequest`
   * instances and returns one `BatchOrderResult` per order, in the same order:
   * `{ order }` on success, `{ error }` on a per-order rejection. Throws only
   * on a whole-request failure (auth, transport).
   */
  placeBatch(requests: Array<OrderRequest>): Array<BatchOrderResult>
}

/** API credentials for a venue. */
export declare class Credentials {
  constructor(apiKey: string, apiSecret: string, passphrase?: string | undefined | null, privateKey?: string | undefined | null)
}

/**
 * A live derivatives (futures/perpetual) client: positions, leverage, margin
 * mode and reduce-only close. Available on the eight venues with futures markets.
 */
export declare class Derivatives {
  /** Connect a USDⓈ-M futures client for `name`. Throws for a spot-only venue. */
  static connect(name: string, credentials: Credentials, testnet?: boolean | undefined | null): Derivatives
  /** Open positions, optionally filtered to one `market`. */
  positions(market?: string | undefined | null): Array<PositionInfo>
  /** Set the leverage for `market`. */
  setLeverage(market: string, leverage: number): void
  /** Set the margin mode for `market` (`"cross"` or `"isolated"`). */
  setMarginMode(market: string, mode: string): void
  /** Flatten the open position in `market` with a reduce-only market order. */
  closePosition(market: string): OrderInfo
}

/** A unified exchange client over the synchronous, pull-based API. */
export declare class Exchange {
  /**
   * An offline paper account seeded from `balances` (asset -> amount), with
   * optional maker/taker fees and slippage in basis points.
   */
  static paper(balances: Record<string, number>, makerBps?: number | undefined | null, takerBps?: number | undefined | null, slippageBps?: number | undefined | null): Exchange
  /**
   * A replay account driven by a recorded price `tape` of `market` trades,
   * filling against a paper book seeded from `balances`.
   */
  static replayTrades(market: string, tape: Array<number>, balances: Record<string, number>, makerBps?: number | undefined | null, takerBps?: number | undefined | null, slippageBps?: number | undefined | null): Exchange
  /**
   * A live client for `name` (see the crate README for the ten supported
   * venues), authenticated with `credentials`.
   */
  static connect(name: string, credentials: Credentials, testnet?: boolean | undefined | null): Exchange
  /** The venue's lowercase identifier (`"paper"`, `"replay"`, `"binance"`, ...). */
  name(): string
  /** Set the mark price a paper account fills against (paper backend only). */
  setPrice(market: string, price: number): void
  /** Place an order; returns the resulting order. */
  placeOrder(request: OrderRequest): OrderInfo
  /** Cancel an open order by venue id. */
  cancelOrder(market: string, orderId: string): void
  /** The current ticker for `market`. */
  ticker(market: string): TickerInfo
  /** Account balances as an `asset -> free amount` map. */
  balances(): Record<string, number>
  /** Subscribe to the public trade stream for `market`. */
  subscribeTrades(market: string): void
  /** Drain all events buffered since the last call. */
  pollEvents(): Array<StreamEvent>
}

/** An order request, built with the market/limit factory methods. */
export declare class OrderRequest {
  static marketBuy(market: string, quantity: number): OrderRequest
  static marketSell(market: string, quantity: number): OrderRequest
  static limitBuy(market: string, quantity: number, price: number): OrderRequest
  static limitSell(market: string, quantity: number, price: number): OrderRequest
}

/**
 * One order's outcome in a batch placement. Exactly one of `order` / `error`
 * is set: `order` on success, `error` with the venue's message on rejection.
 */
export interface BatchOrderResult {
  order?: OrderInfo
  error?: string
}

/** An order as reported by the exchange. */
export interface OrderInfo {
  id: string
  clientOrderId?: string
  symbol: string
  side: string
  status: string
  quantity: number
  filledQuantity: number
  price?: number
  averagePrice?: number
}

/** A derivatives position. */
export interface PositionInfo {
  symbol: string
  side: string
  quantity: number
  entryPrice: number
  markPrice: number
  leverage: number
  unrealizedPnl: number
  marginMode: string
}

/**
 * A single stream event. `kind` discriminates the payload
 * (`"trade"`, `"ticker"`, `"order_update"`, `"balance_update"`, ...).
 */
export interface StreamEvent {
  kind: string
  symbol?: string
  price?: number
  quantity?: number
  side?: string
  timestamp?: number
  order?: OrderInfo
  balances?: Record<string, number>
  channel?: string
}

/** A point-in-time ticker. */
export interface TickerInfo {
  symbol: string
  last: number
  bid: number
  ask: number
  volume: number
}

/** Library version (matches the Rust crate version). */
export declare function version(): string
