/* auto-generated by NAPI-RS */
/* eslint-disable */
/** API credentials for a venue. */
export declare class Credentials {
  constructor(apiKey: string, apiSecret: string, passphrase?: string | undefined | null, privateKey?: string | undefined | null)
}

/** A unified exchange client over the synchronous, pull-based API. */
export declare class Exchange {
  /**
   * An offline paper account seeded from `balances` (asset -> amount), with
   * optional maker/taker fees and slippage in basis points.
   */
  static paper(balances: Record<string, number>, makerBps?: number | undefined | null, takerBps?: number | undefined | null, slippageBps?: number | undefined | null): Exchange
  /**
   * A replay account driven by a recorded price `tape` of `market` trades,
   * filling against a paper book seeded from `balances`.
   */
  static replayTrades(market: string, tape: Array<number>, balances: Record<string, number>, makerBps?: number | undefined | null, takerBps?: number | undefined | null, slippageBps?: number | undefined | null): Exchange
  /**
   * A live client for `name` (see the crate README for the ten supported
   * venues), authenticated with `credentials`.
   */
  static connect(name: string, credentials: Credentials, testnet?: boolean | undefined | null): Exchange
  /** The venue's lowercase identifier (`"paper"`, `"replay"`, `"binance"`, ...). */
  name(): string
  /** Set the mark price a paper account fills against (paper backend only). */
  setPrice(market: string, price: number): void
  /** Place an order; returns the resulting order. */
  placeOrder(request: OrderRequest): OrderInfo
  /** Cancel an open order by venue id. */
  cancelOrder(market: string, orderId: string): void
  /** The current ticker for `market`. */
  ticker(market: string): TickerInfo
  /** Account balances as an `asset -> free amount` map. */
  balances(): Record<string, number>
  /** Subscribe to the public trade stream for `market`. */
  subscribeTrades(market: string): void
  /** Drain all events buffered since the last call. */
  pollEvents(): Array<StreamEvent>
}

/** An order request, built with the market/limit factory methods. */
export declare class OrderRequest {
  static marketBuy(market: string, quantity: number): OrderRequest
  static marketSell(market: string, quantity: number): OrderRequest
  static limitBuy(market: string, quantity: number, price: number): OrderRequest
  static limitSell(market: string, quantity: number, price: number): OrderRequest
}

/** An order as reported by the exchange. */
export interface OrderInfo {
  id: string
  clientOrderId?: string
  symbol: string
  side: string
  status: string
  quantity: number
  filledQuantity: number
  price?: number
  averagePrice?: number
}

/**
 * A single stream event. `kind` discriminates the payload
 * (`"trade"`, `"ticker"`, `"order_update"`, `"balance_update"`, ...).
 */
export interface StreamEvent {
  kind: string
  symbol?: string
  price?: number
  quantity?: number
  side?: string
  timestamp?: number
  order?: OrderInfo
  balances?: Record<string, number>
  channel?: string
}

/** A point-in-time ticker. */
export interface TickerInfo {
  symbol: string
  last: number
  bid: number
  ask: number
  volume: number
}

/** Library version (matches the Rust crate version). */
export declare function version(): string
